name: Webhook on Event
# Make sure to change what triggers your action based on your needs
on: [milestone, create, delete, fork, issues, member, pull_request, pull_request_review, issue_comment, push]
jobs:
  # ID of our job
  webhook-request:
    # OS to run our job on
    runs-on: ubuntu-latest
    steps:
    - name: Send a request to webhook
      run: |
        RESPONSE=$(curl -H "Content-Type: application/json" -X POST -d '{
        "username": "GitHub",
        "content": "@everyone",
        "embeds": [
          {
            "type": "rich",
            "title": "New Changes",
            "description": "Nya ändringar på backend av: ${{ github.actor }}",
            "color": 2123412,
            "author": {
              "name": "${{ github.actor }}",
              "url": "https://github.com/${{ github.actor_id }}",
              "icon_url": "https://avatars.githubusercontent.com/u/${{ github.actor_id }}?v=4"
            },
            "url": "https://github.com/CarlosDevCoding/paketeringbackend"
          }
        ]
        }' ${{ secrets.WEBHOOK_URL }})
        echo "Webhook server response: $RESPONSE"
